<?php 
//Export Module 'cp_users' Date: 31-05-2019 10:11:07Byadmin
global $db;
if(!$result_insert_modul = $db->Query("insert into sys_modules (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('cp_users', 'Gestion utilisateurs','cp_users/main','radcheck','cp_users',NULL,'0', '1', '[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'cp_users' </li>";}
  //Workflow '59' 'Création cp_users'
  if(!$result_task_59 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Création cp_users', $result_insert_modul, '0', 'creat_cp_users', 'warning', 'Attente Validation', '<span class=\"label label-sm label-warning\">Attente Validation</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import Workflow 'Création cp_users' </li>";}
  //Workflow '60' 'Validation  cp_users'
  if(!$result_task_60 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Validation  cp_users', $result_insert_modul, '1', 'valid_cp_users', 'success', 'Compte Actif', '<span class=\"label label-sm label-success\">Compte Actif</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import Workflow 'Validation  cp_users' </li>";}
  //Workflow '61' 'Archive cp_users'
  if(!$result_task_61 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Archive cp_users', $result_insert_modul, '100', 'archive_cp_users', 'inverse', 'Ligne Archivée', '<span class=\"label label-sm label-inverse\">Ligne Archivée</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import Workflow 'Archive cp_users' </li>";}
  //Workflow '62' 'Suppression cp_users'
  if(!$result_task_62 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Suppression cp_users', $result_insert_modul, '200', 'delete_cp_users', 'danger', 'Ligne Supprimée', '<span class=\"label label-sm label-danger\">Ligne Supprimée</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import Workflow 'Suppression cp_users' </li>";}
  //Workflow '63' 'Utilisateur bloqué'
  if(!$result_task_63 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Utilisateur bloqué', $result_insert_modul, '2', 'block_cp_users', 'danger', 'Utiliateur Bloqué', '<span class=\"label label-sm label-danger\">Utiliateur Bloqué</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import Workflow 'Utilisateur bloqué' </li>";}
  //Workflow '64' 'Quota epuisé'
  if(!$result_task_64 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Quota epuisé', $result_insert_modul, '3', 'quota_cp_users', 'info', 'Solde epuisé', '<span class=\"label label-sm label-info\">Solde epuisé</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import Workflow 'Quota epuisé' </li>";}
  //Task 'cp_users' 'Gestion utilisateurs'
  if(!$result_task_1236 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('cp_users', $result_insert_modul, 'cp_users','cp_users/main', '1', 'Gestion utilisateurs', 'user-circle', '1', '0', '0','list', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion utilisateurs' </li>";}
      // Action Task 1236 - 'Gestion utilisateurs'
      if(!$result_action_2075 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '02e6dd76bcda0f6a4718d1e9393d3ecc', 'Gestion utilisateurs','cp_users', 'this_url', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion utilisateurs' </li>";}
      // Action Task 1236 - 'Editer cp_users'
      if(!$result_action_2078 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '0ae4cf0c37bb72e060aecf588eb3a17e', 'Editer cp_users','edit_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"edit_cp_users\"  ><i class=\"ace-icon fa fa-pencil-square-o blue bigger-100\"></i> Editer cp_users</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer cp_users' </li>";}
      // Action Task 1236 - 'Valider cp_users'
      if(!$result_action_2080 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '3aff5ef974805341c8792f265feab324', 'Valider cp_users','valid_cp_users', 'this_exec', '".'<li><a href=\"#\" class=\"this_exec\" data=\"%id%\" rel=\"valid_cp_users\"  ><i class=\"ace-icon fa fa-check-square-o green bigger-100\"></i> Valider cp_users</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider cp_users' </li>";}
      // Action Task 1236 - 'Archiver cp_users'
      if(!$result_action_2082 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '60d2b8f1cc08d0a664cd268feb3704d1', 'Archiver cp_users','archive_cp_users', 'this_exec', '".'<li><a href=\"#\" class=\"this_exec\" data=\"%id%\" rel=\"archive_cp_users\"  ><i class=\"ace-icon fa fa-archive bigger-100\"></i> Archiver cp_users</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Archiver cp_users' </li>";}
      // Action Task 1236 - 'Détail Utilisateur CP'
      if(!$result_action_2086 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, 'f31f56fd67d966ba161b2855acadc723', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"details_cp_users\"  ><i class=\"ace-icon fa fa-eye green bigger-100\"></i> Détail Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
      // Action Task 1236 - 'Détail Utilisateur CP'
      if(!$result_action_2087 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '7b55d9582dbebc69aeeba5f2d8afc0f2', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"details_cp_users\"  ><i class=\"ace-icon fa fa-eye green bigger-100\"></i> Détail Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '1', '0', 'Ligne validée','success','".'<span class="label label-sm label-success">Ligne validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
      // Action Task 1236 - 'Détail Utilisateur CP'
      if(!$result_action_2088 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '9ec1a0759ad35a33de542a1f51bc0ffa', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"details_cp_users\"  ><i class=\"ace-icon fa fa-eye green bigger-100\"></i> Détail Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '100', '0', 'Ligne Archivée','inverse','".'<span class="label label-sm label-inverse">Ligne Archivée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
      // Action Task 1236 - 'Détail Utilisateur CP'
      if(!$result_action_2089 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '041c9a15b62da24c8922fbc55f65042e', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"details_cp_users\"  ><i class=\"ace-icon fa fa-eye green bigger-100\"></i> Détail Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '200', '0', 'Ligne Supprimée','danger','".'<span class="label label-sm label-danger">Ligne Supprimée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
      // Action Task 1236 - 'Détail Utilisateur CP'
      if(!$result_action_2090 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, 'f31f56fd67d966ba161b2855acadc724', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"details_cp_users\"  ><i class=\"ace-icon fa fa-eye green bigger-100\"></i> Détail Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '2', '0', 'Utilisateur bloqué','warning','".'<span class="label label-sm label-warning">Utilisateur bloqué</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
      // Action Task 1236 - 'Bloquer Utilisateur CP'
      if(!$result_action_2092 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '486b46c0ca63912718d5a1cce494875b', 'Bloquer Utilisateur CP','bloque_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_modal\" data=\"%id%\" rel=\"bloque_cp_users\"  ><i class=\"ace-icon fa fa-ban red bigger-100\"></i> Bloquer Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"3\"]', '1', '0', 'Ligne validée','success','".'<span class="label label-sm label-success">Ligne validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Bloquer Utilisateur CP' </li>";}
      // Action Task 1236 - 'Détail Utilisateur CP'
      if(!$result_action_2093 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, 'f31f56fd67d966ba161b2855acadc722', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".'<li><a href=\"#\" class=\"this_url\" data=\"%id%\" rel=\"details_cp_users\"  ><i class=\"ace-icon fa fa-eye green bigger-100\"></i> Détail Utilisateur CP</a></li>'."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '3', '0', 'Solde epuisé','warning','".'<span class="label label-sm label-warning">Solde epuisé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
      // Action Task 1236 - 'Débloquer utilisateur'
      if(!$result_action_2096 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '7bb9f71067dd26af137cd6f077ecdb83', 'Débloquer utilisateur','deblpoquer_cp_user', 'this_exec', '".'<li><a href=\"#\" class=\"this_exec\" data=\"%id%\" rel=\"deblpoquer_cp_user\"  ><i class=\"ace-icon fa fa-unlock bigger-100\"></i> Débloquer utilisateur</a></li>'."', '0', '[\"1\",\"6\",\"5\",\"3\",\"7\"]', '2', '0', 'Utiliateur Bloqué','danger','".'<span class="label label-sm label-danger">Utiliateur Bloqué</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer utilisateur' </li>";}
      // Action Task 1236 - 'Débloquer utilisateur'
      if(!$result_action_2097 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, 'dfc093e5d536db367757b4c76883c580', 'Débloquer utilisateur','deblpoquer_cp_user', 'this_exec', '".'<li><a href=\"#\" class=\"this_exec\" data=\"%id%\" rel=\"deblpoquer_cp_user\"  ><i class=\"ace-icon fa fa-unlock bigger-100\"></i> Débloquer utilisateur</a></li>'."', '0', '[\"1\",\"6\",\"5\",\"3\",\"7\"]', '3', '0', 'Solde epuisé','info','".'<span class="label label-sm label-info">Solde epuisé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer utilisateur' </li>";}
      // Action Task 1236 - 'Effacer compte'
      if(!$result_action_2101 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, 'edc36db41f112c3e5654e109c1eba732', 'Effacer compte','delete_cp_user', 'this_exec', '".'<li><a href=\"#\" class=\"this_exec\" data=\"%id%\" rel=\"delete_cp_user\"  ><i class=\"ace-icon fa fa-trash bigger-100\"></i> Effacer compte</a></li>'."', '0', '[\"1\",\"2\",\"5\",\"7\"]', '2', '0', 'Utiliateur Bloqué','danger','".'<span class="label label-sm label-danger">Utiliateur Bloqué</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Effacer compte' </li>";}
      // Action Task 1236 - 'Effacer compte'
      if(!$result_action_2102 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1236, '28af0ebbee4c87f5d03426179eb2b90c', 'Effacer compte','delete_cp_user', 'this_exec', '".'<li><a href=\"#\" class=\"this_exec\" data=\"%id%\" rel=\"delete_cp_user\"  ><i class=\"ace-icon fa fa-trash bigger-100\"></i> Effacer compte</a></li>'."', '0', '[\"1\",\"2\",\"5\",\"7\"]', '3', '0', 'Solde epuisé','info','".'<span class="label label-sm label-info">Solde epuisé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Effacer compte' </li>";}
  //Task 'add_cp_users' 'Ajouter cp_users'
  if(!$result_task_1237 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_cp_users', $result_insert_modul, 'add_cp_users','cp_users/main', '1', 'Ajouter cp_users', NULL, '1', '0', '0','formadd', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter cp_users' </li>";}
      // Action Task 1237 - 'Ajouter cp_users'
      if(!$result_action_2076 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1237, 'dbc813bd29e7c095c00ca3b9d23f0b08', 'Ajouter cp_users','add_cp_users', 'this_url', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter cp_users' </li>";}
  //Task 'edit_cp_users' 'Editer cp_users'
  if(!$result_task_1238 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_cp_users', $result_insert_modul, 'edit_cp_users','cp_users/main', '1', 'Editer cp_users', NULL, '1', '0', '0','formedit', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer cp_users' </li>";}
      // Action Task 1238 - 'Editer cp_users'
      if(!$result_action_2077 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1238, '2aef26d655ea66955585ab06f30bccb1', 'Editer cp_users','edit_cp_users', 'this_url', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer cp_users' </li>";}
  //Task 'valid_cp_users' 'Valider cp_users'
  if(!$result_task_1239 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('valid_cp_users', $result_insert_modul, 'valid_cp_users','cp_users/main', '1', 'Valider cp_users', NULL, '1', '0', '0','exec', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider cp_users' </li>";}
      // Action Task 1239 - 'Valider cp_users'
      if(!$result_action_2079 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1239, 'f2e6f3918edd8bc0890c95e86e2128ff', 'Valider cp_users','valid_cp_users', 'this_exec', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '1', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider cp_users' </li>";}
  //Task 'archive_cp_users' 'Archiver cp_users'
  if(!$result_task_1240 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('archive_cp_users', $result_insert_modul, 'archive_cp_users','cp_users/main', '1', 'Archiver cp_users', NULL, '1', '0', '0','exec', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Archiver cp_users' </li>";}
      // Action Task 1240 - 'Archiver cp_users'
      if(!$result_action_2081 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1240, 'fd312741f2506dca6ceb4c87104bfefb', 'Archiver cp_users','archive_cp_users', 'this_exec', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Archiver cp_users' </li>";}
  //Task 'delete_cp_users' 'Supprimer cp_users'
  if(!$result_task_1241 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('delete_cp_users', $result_insert_modul, 'delete_cp_users','cp_users/main', '1', 'Supprimer cp_users', NULL, '1', '0', '0','exec', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer cp_users' </li>";}
      // Action Task 1241 - 'Supprimer cp_users'
      if(!$result_action_2083 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1241, 'ef868279b89b17c365aaad8204c7ae66', 'Supprimer cp_users','delete_cp_users', 'this_exec', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer cp_users' </li>";}
      // Action Task 1241 - 'Supprimer cp_users'
      if(!$result_action_2098 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1241, 'ef868279b89b17c365aaad8204c7ae66', 'Supprimer cp_users','delete_cp_users', 'this_exec', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '2', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer cp_users' </li>";}
      // Action Task 1241 - 'Supprimer cp_users'
      if(!$result_action_2099 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1241, 'ef868279b89b17c365aaad8204c7ae66', 'Supprimer cp_users','delete_cp_users', 'this_exec', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '3', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer cp_users' </li>";}
  //Task 'details_cp_users' 'Détail Utilisateur CP'
  if(!$result_task_1242 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('details_cp_users', $result_insert_modul, 'details_cp_users','cp_users/main', '1', 'Détail Utilisateur CP', 'eye green', '1', '0', '0','profil', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détail Utilisateur CP' </li>";}
      // Action Task 1242 - 'Détail Utilisateur CP'
      if(!$result_action_2085 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1242, '4dfc998c543862968d030997f288c18f', 'Détail Utilisateur CP','details_cp_users', 'this_url', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Utilisateur CP' </li>";}
  //Task 'bloque_cp_users' 'Bloquer Utilisateur CP'
  if(!$result_task_1243 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('bloque_cp_users', $result_insert_modul, 'bloque_cp_users','cp_users/main', '1', 'Bloquer Utilisateur CP', 'ban red', '1', '0', '0','formpers', '[\"1\",\"2\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Bloquer Utilisateur CP' </li>";}
      // Action Task 1243 - 'Bloquer Utilisateur CP'
      if(!$result_action_2091 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1243, '393644beaa6eceae3038fc3b76bfd536', 'Bloquer Utilisateur CP','bloque_cp_users', 'this_url', '".NULL."', '0', '[\"1\",\"2\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Bloquer Utilisateur CP' </li>";}
  //Task 'cp_users_connexions' 'Connexions User CP'
  if(!$result_task_1244 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('cp_users_connexions', $result_insert_modul, 'cp_users_connexions','cp_users/main', '1', 'Connexions User CP', 'exchange', '1', '0', '0','list', '[\"1\",\"2\",\"4\",\"3\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Connexions User CP' </li>";}
      // Action Task 1244 - 'Connexions User CP'
      if(!$result_action_2094 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1244, '60d938d0b300361d2b9e5afcc52cfd51', 'Connexions User CP','cp_users_connexions', 'this_url', '".NULL."', '0', '[\"1\",\"2\",\"4\",\"3\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Connexions User CP' </li>";}
  //Task 'deblpoquer_cp_user' 'Débloquer utilisateur'
  if(!$result_task_1245 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deblpoquer_cp_user', $result_insert_modul, 'deblpoquer_cp_user','cp_users/main', '1', 'Débloquer utilisateur', 'unlock', '1', '0', '0','exec', '[\"1\",\"6\",\"5\",\"3\",\"7\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Débloquer utilisateur' </li>";}
      // Action Task 1245 - 'Débloquer utilisateur'
      if(!$result_action_2095 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1245, '7b7aca3dda31cb518741a6ff38d6e670', 'Débloquer utilisateur','deblpoquer_cp_user', 'this_exec', '".NULL."', '0', '[\"1\",\"6\",\"5\",\"3\",\"7\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer utilisateur' </li>";}
  //Task 'delete_cp_user' 'Effacer compte'
  if(!$result_task_1246 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('delete_cp_user', $result_insert_modul, 'delete_cp_user','cp_users/main', '1', 'Effacer compte', 'trash', '1', '0', '0','exec', '[\"1\",\"2\",\"5\",\"7\"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Effacer compte' </li>";}
      // Action Task 1246 - 'Effacer compte'
      if(!$result_action_2100 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1246, '85ebf299e3a891b1e80bbcd5d0e29578', 'Effacer compte','delete_cp_user', 'this_exec', '".NULL."', '0', '[\"1\",\"2\",\"5\",\"7\"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Effacer compte' </li>";}
