<?php 
//Export Module 'stock_approvisionnement' Date: 24-12-2018 08:00:55Byadmin
global $db;
if(!$result_insert_modul = $db->Query("insert into sys_modules (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('stock_approvisionnement', 'Approvisionnement','stock/submodul/stock_approvisionnement','stk_approvisionnement','stock_approvisionnement','stock','2', '1', '["1","2","3","5"]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'stock_approvisionnement' </li>";}
  //Workflow '17' 'Création Approvisionnement Stock'
  if(!$result_task_17 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Création Approvisionnement Stock', $result_insert_modul, ,'0', 'creat_appro', 'warning', NULL, '<span class="label label-sm label-warning">Attente de validation</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import task 'Création Approvisionnement Stock' </li>";}
  //Workflow '18' 'Validation Approvisionnement Stock'
  if(!$result_task_18 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Validation Approvisionnement Stock', $result_insert_modul, ,'1', 'valid_appro', 'info', 'Attente réception entrepôt', '<span class="label label-sm label-info">Attente réception entrepôt</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation Approvisionnement Stock' </li>";}
  //Workflow '19' 'Réception Approvisionnement Stock'
  if(!$result_task_19 = $db->Query("INSERT INTO sys_workflow (descrip, modul_id, etat_line, code, color, etat_desc, message_etat, creusr)VALUES('Réception Approvisionnement Stock', $result_insert_modul, ,'2', 'recep_appro', 'success', 'Approvisionnement terminé', '<span class="label label-sm label-success">Approvisionnement terminé</span>', '1')")){$this->error = false; $this->log .= "<li> Error Import task 'Réception Approvisionnement Stock' </li>";}
  //Task 'stock_approvisionnement' 'Approvisionnement Stock'
  if(!$result_task_1167 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('stock_approvisionnement', $result_insert_modul, 'stock_approvisionnement','stock/submodul/stock_approvisionnement', '1', 'Approvisionnement Stock', 'cart-plus', '1', '0', '0','list', '["1","2","3","5"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Approvisionnement Stock'
      if(!$result_action_1941 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, 'e38221c20c8f333859c83c085b2da1e3', 'Approvisionnement Stock','stock_approvisionnement', 'this_url', '".NULL."', '0', '["1","2","3","5"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Modifier Approvisionnement Stock'
      if(!$result_action_1944 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, '5ab6dd1e710a814fe2fa6a8769143e4a', 'Modifier Approvisionnement Stock','edit_stock_approvisionnement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edit_stock_approvisionnement"  ><i class="ace-icon fa fa-pencil blue bigger-100"></i> Modifier Approvisionnement Stock</a></li>'."', '0', '["1","2","3","5"]', '0', '0', 'Attente validation',NULL,'".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Valider Approvisionnement Stock'
      if(!$result_action_1947 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, '29e79eed8b60656aa17e23e5e0b712ca', 'Valider Approvisionnement Stock','valid_stock_approvisionnement', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="valid_stock_approvisionnement"  ><i class="ace-icon fa fa-check bigger-100"></i> Valider Approvisionnement Stock</a></li>'."', '0', '["1","2","3","5"]', '0', '1', 'Attente validation',NULL,'".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Réception Approvisionnement Stock'
      if(!$result_action_1959 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, '20ed0d66f672443bd477aa40c4816b5f', 'Réception Approvisionnement Stock','reception_approvisionnement_stock', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="reception_approvisionnement_stock"  ><i class="ace-icon fa fa-cart-arrow-down bigger-100"></i> Réception Approvisionnement Stock</a></li>'."', '0', '["1","2","3","5","6"]', '1', '0', 'Attente réception entrepôt',NULL,'".'<span class="label label-sm label-info">Attente réception entrepôt</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Réception Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Détails Approvisionnement Stock'
      if(!$result_action_1961 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, 'a626b0b8697098c376981279877a2319', 'Détails Approvisionnement Stock','detail_stock_approvisionnement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detail_stock_approvisionnement"  ><i class="ace-icon fa fa-eye green bigger-100"></i> Détails Approvisionnement Stock</a></li>'."', '0', '["1","2","3","5","6"]', '0', '0', NULL,NULL,'".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Détails Approvisionnement Stock'
      if(!$result_action_1962 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, 'a0d345722b4e0c9fb922ca7c00342fbe', 'Détails Approvisionnement Stock','detail_stock_approvisionnement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detail_stock_approvisionnement"  ><i class="ace-icon fa fa-eye green bigger-100"></i> Détails Approvisionnement Stock</a></li>'."', '0', '["1","2","3","5","6"]', '1', '0', 'Attente réception entrepôt',NULL,'".'<span class="label label-sm label-info">Attente réception entrepôt</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Approvisionnement Stock' </li>";}
      // Action Task 1167 - 'Détails Approvisionnement Stock'
      if(!$result_action_1963 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, 'f1092b21a411f8d4c5fc0fc4bd620702', 'Détails Approvisionnement Stock','detail_stock_approvisionnement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detail_stock_approvisionnement"  ><i class="ace-icon fa fa-eye green bigger-100"></i> Détails Approvisionnement Stock</a></li>'."', '0', '["1","2","3","5","6"]', '2', '0', 'Approvisionnement terminé','success','".'<span class="label label-sm label-success">Approvisionnement terminé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Approvisionnement Stock' </li>";}
  //Task 'add_stock_approvisionnement' 'Ajouter Approvisionnement Stock'
  if(!$result_task_1168 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_stock_approvisionnement', $result_insert_modul, 'add_stock_approvisionnement','stock/submodul/stock_approvisionnement', '1', 'Ajouter Approvisionnement Stock', NULL, '1', '0', '0','formadd', '["1","2","3","5"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Approvisionnement Stock' </li>";}
      // Action Task 1168 - 'Ajouter Approvisionnement Stock'
      if(!$result_action_1942 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1168, '70f5f739904bac438195724ccd0240af', 'Ajouter Approvisionnement Stock','add_stock_approvisionnement', 'this_url', '".NULL."', '0', '["1","2","3","5"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Approvisionnement Stock' </li>";}
  //Task 'edit_stock_approvisionnement' 'Modifier Approvisionnement Stock'
  if(!$result_task_1169 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_stock_approvisionnement', $result_insert_modul, 'edit_stock_approvisionnement','stock/submodul/stock_approvisionnement', '1', 'Modifier Approvisionnement Stock', NULL, '1', '0', '0','formedit', '["1","2","3","5"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Approvisionnement Stock' </li>";}
      // Action Task 1169 - 'Modifier Approvisionnement Stock'
      if(!$result_action_1943 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1169, '46282b09b8ca41cbb51112a1f0ff2505', 'Modifier Approvisionnement Stock','edit_stock_approvisionnement', 'this_url', '".NULL."', '0', '["1","2","3","5"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Approvisionnement Stock' </li>";}
  //Task 'add_stock_approvisionnement_charge' 'Ajouter Approvisionnement Stock Charge'
  if(!$result_task_1170 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_stock_approvisionnement_charge', $result_insert_modul, 'add_stock_approvisionnement_charge','stock/submodul/stock_approvisionnement', '1', 'Ajouter Approvisionnement Stock Charge', NULL, '1', '0', '0','formadd', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Approvisionnement Stock Charge' </li>";}
      // Action Task 1170 - 'Ajouter Approvisionnement Stock Charge'
      if(!$result_action_1945 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1170, 'a1479ba9eb7f7244fecd712e64440520', 'Ajouter Approvisionnement Stock Charge','add_stock_approvisionnement_charge', 'this_url', '".NULL."', '0', 'null', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Approvisionnement Stock Charge' </li>";}
  //Task 'valid_stock_approvisionnement' 'Valider Approvisionnement Stock'
  if(!$result_task_1171 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('valid_stock_approvisionnement', $result_insert_modul, 'valid_stock_approvisionnement','stock/submodul/stock_approvisionnement', '1', 'Valider Approvisionnement Stock', NULL, '1', '0', '0','exec', '["1","2","3","5"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Approvisionnement Stock' </li>";}
      // Action Task 1171 - 'Valider Approvisionnement Stock'
      if(!$result_action_1946 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1171, 'b1a209e90a46a9368d7d5a56c95fc7ac', 'Valider Approvisionnement Stock','valid_stock_approvisionnement', 'this_exec', '".NULL."', '0', '["1","2","3","5"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Approvisionnement Stock' </li>";}
  //Task 'edit_stock_approvisionnement_charge' 'Modifier Approvisionnement Stock Charge'
  if(!$result_task_1173 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_stock_approvisionnement_charge', $result_insert_modul, 'edit_stock_approvisionnement_charge','stock/submodul/stock_approvisionnement', '1', 'Modifier Approvisionnement Stock Charge', NULL, '1', '0', '0','formedit', '["1","2","3","5"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Approvisionnement Stock Charge' </li>";}
      // Action Task 1173 - 'Modifier Approvisionnement Stock Charge'
      if(!$result_action_1949 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1173, 'e452bf26aace328113321cf3041c0ac9', 'Modifier Approvisionnement Stock Charge','edit_stock_approvisionnement_charge', 'this_url', '".NULL."', '0', '["1","2","3","5"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Approvisionnement Stock Charge' </li>";}
  //Task 'delete_stock_approvisionnement' 'Supprimer Approvisionnement'
  if(!$result_task_1175 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('delete_stock_approvisionnement', $result_insert_modul, 'delete_stock_approvisionnement','stock/submodul/stock_approvisionnement', '1', 'Supprimer Approvisionnement', NULL, '1', '0', '0','exec', '["1","2","3"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Approvisionnement' </li>";}
      // Action Task 1175 - 'Supprimer Approvisionnement'
      if(!$result_action_1952 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1175, 'e6408f2a53c762a165bd0c136552aef8', 'Supprimer Approvisionnement','delete_stock_approvisionnement', 'this_exec', '".NULL."', '0', '["1","2","3"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Approvisionnement' </li>";}
  //Task 'reception_approvisionnement_stock' 'Réception Approvisionnement Stock'
  if(!$result_task_1178 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('reception_approvisionnement_stock', $result_insert_modul, 'reception_approvisionnement_stock','stock/submodul/stock_approvisionnement', '1', 'Réception Approvisionnement Stock', NULL, '1', '0', '0','formpers', '["1","2","3","5","6"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Réception Approvisionnement Stock' </li>";}
      // Action Task 1178 - 'Réception Approvisionnement Stock'
      if(!$result_action_1958 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1178, 'f53e4719266a1cde4ce23c9aaf6af541', 'Réception Approvisionnement Stock','reception_approvisionnement_stock', 'this_url', '".NULL."', '0', '["1","2","3","5","6"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Réception Approvisionnement Stock' </li>";}
  //Task 'detail_stock_approvisionnement' 'Détails Approvisionnement Stock'
  if(!$result_task_1179 = $db->Query("INSERT INTO sys_task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detail_stock_approvisionnement', $result_insert_modul, 'detail_stock_approvisionnement','stock/submodul/stock_approvisionnement', '1', 'Détails Approvisionnement Stock', NULL, '1', '0', '0','profil', '["1","2","3","5","6"]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Approvisionnement Stock' </li>";}
      // Action Task 1179 - 'Détails Approvisionnement Stock'
      if(!$result_action_1960 = $db->Query("INSERT INTO sys_task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1179, '11e3d2c515d5b645c13650272efe9f26', 'Détails Approvisionnement Stock','detail_stock_approvisionnement', 'this_url', '".NULL."', '0', '["1","2","3","5","6"]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Approvisionnement Stock' </li>";}
